# @package _global_
module:
  _target_: emg2qwerty.lightning.CNNRNNCTCModule
  in_features: 528
  mlp_features: [384]
  block_channels: [24, 24, 24, 24]
  kernel_width: 32
  
  # New LSTM Parameters
  rnn_hidden_size: 256    # Number of hidden units in the LSTM
  rnn_num_layers: 2  # Number of stacked LSTM layers
  bidirectional: True  # Use BiLSTM for better sequence modeling

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context
