# @package _global_
module:
  _target_: emg2qwerty.lightning.RNNCTCModule
  in_features: 528 
  mlp_features: [384]
  rnn_hidden_size: 256
  rnn_num_layers: 3
  bidirectional: True

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context
